# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.accenture.alastria.com:

networks:
  byfn:

services:

  peer0.accenture.alastria.com:
    container_name: peer0.accenture.alastria.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.accenture.alastria.com
      - CORE_PEER_ADDRESS=peer0.accenture.alastria.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.accenture.alastria.com:7051
      - CORE_PEER_LOCALMSPID=AccentureMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./upscale//channel-artifacts/crypto-config/peerOrganizations/accenture.alastria.com/peers/peer0.accenture.alastria.com/msp:/etc/hyperledger/fabric/msp
        - ./upscale/channel-artifacts/crypto-config/peerOrganizations/accenture.alastria.com/peers/peer0.accenture.alastria.com/tls:/etc/hyperledger/fabric/tls
        - peer0.accenture.alastria.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - byfn

  

  Org3cli:
    container_name: cli-accenture
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli-accenture
      - CORE_PEER_ADDRESS=peer0.accenture.alastria.com:7051
      - CORE_PEER_LOCALMSPID=AccentureMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accenture.alastria.com/peers/peer0.accenture.alastria.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accenture.alastria.com/peers/peer0.accenture.alastria.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accenture.alastria.com/peers/peer0.accenture.alastria.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/accenture.alastria.com/users/Admin@accenture.alastria.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./upscale/channel-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./upscale/:/opt/gopath/src/github.com/hyperledger/fabric/peer/upscale
    depends_on:
      - peer0.accenture.alastria.com
    networks:
      - byfn
